
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/jpatest?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username: root
        password: 1234

jpa:
    hibernate:
        ddl-auto: create  # 第一次简表create  后面用update
        show-sql: true


server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        max-connections: 20000
        min-spare-threads: 30
    port: 8089
    servlet:
        context-path: /